### ISSUE TITLE
Support Request:

### ISSUE THREAD

**Issue by marksmith1701** [homebridge-plugins/homebridge-august#58]
### Describe Your Problem

after multiple tries it won't connect to v4 lock

### Relevant log output

```shell
FetchError: Status 429 (undefined): undefined
[04/05/2023, 14:21:39] [August] Discover Devices: TypeError: Cannot convert undefined or null to object
```

### Config for homebridge-august

```shell
"name": "August",
            "credentials": {
                "augustId": "xxx@xx.com",
                "password": "xxxxx",
                "installId": "xxx",
                "isValidated": true,
                "notice": "Keep your tokens a secret!"
```

### Device & Model

August smartlock v4

### Node.js Version

v18.16.0

### NPM Version

1.1.0

### Homebridge Version

1.6.1

### Homebridge August Plugin Version

v1.1.0

### Homebridge Config UI X Plugin Version

v

### Operating System

Raspbian

**Comment by pj005975** [comment]
I'm having the exact same issue.

fetcherror: Status 401 (undefined): undefined
[11/05/2023, 08:21:40] [August] Discover Devices: TypeError: Cannot convert undefined or null to object

Node.js version: [v18.12.1]
Homebridge Version: v1.6.1
homebridge-august v1.1.0
homebridge-config-ui-x v4.50.2
OS | Raspbian GNU/Linux Bullseye (11)
Model: August Smart lock with wifi bridge

**Comment by pj005975** [comment]
Solved by following procedure in Bug: Cannot find my 4th Gen lock #38
I accessed : account.august.com and changed my password, deleted the config then restarted the setup and everything worked.

**Comment by marksmith1701** [comment]
still having issues after following that procedure:

[11/05/2023, 12:10:43] [August] refreshStatus: TypeError: Cannot read properties of undefined (reading 'LockID')
[11/05/2023, 12:10:43] [August] Lock: Front Door failed lockStatus (refreshStatus), Error Message: "Cannot read properties of undefined (reading 'LockID')"
FetchError: Status 429 (undefined): undefined
[11/05/2023, 12:10:43] [August] refreshStatus: TypeError: Cannot read properties of undefined (reading 'x-august-access-token')
[11/05/2023, 12:10:43] [August] Lock: Front Door failed lockStatus (refreshStatus), Error Message: "Cannot read properties of undefined (reading 'x-august-access-token')"

**Comment by pj005975** [comment]
I got something like that first time, had to delete the whole config for the plugin (start from fresh)
Then I changed my password from account.august.com
One changed, I logged out from the site and started setting up the plugin.
Got a new verification code, input it in plugin then restart again.
After this it worked.

Sorry if it doesn't work for you.

Apparently the plugin seems to be sending undefined stuff when login is not successful.

**Comment by marksmith1701** [comment]
yea...tried all of that..still getting the same errors.  I will note i have August connects on all 3 of my locks, do you think that can be causing an issue?  when the locks were on their own wifi, i was burning through batteries every 5-6 days.

**Comment by paulcasavant** [comment]
Having this issue with the 4th gen lock.

**Comment by ma2kyd** [comment]
Yep. Reporting in with the same info. 

`FetchError: Status 429 (undefined): undefined
[6/4/2023, 9:56:36 PM] [August] Discover Devices: TypeError: Cannot convert undefined or null to object`

Node.js version: [v18.12.1]
Homebridge Version: v1.6.1
homebridge-august v1.1.0
homebridge-config-ui-x v4.50.2
